# Generated by Django 5.0.14 on 2026-08-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cast/')),
                ('character_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Cast',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True)),
                ('flag', models.CharField(blank=True, help_text='Emoji flag ដូចជា 🇰🇭 🇨🇳 🇰🇷', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('director', 'Director'), ('producer', 'Producer'), ('writer', 'Writer'), ('cinematographer', 'Cinematographer'), ('composer', 'Composer'), ('other', 'Other')], default='other', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crew/')),
            ],
            options={
                'verbose_name_plural': 'Crew',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeriesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True)),
                ('flag', models.CharField(blank=True, help_text='Emoji flag ដូចជា 🇨🇳 🇺🇸 🇰🇷', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Series Types',
                'ordering': ['name'],
            },
        ),
    ]
