# Generated by Django 5.0.14 on 2026-08-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0005_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True)),
                ('flag', models.CharField(blank=True, help_text='Emoji flag ដូចជា 🇨🇳 🇺🇸 🇰🇷', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Series Types',
                'ordering': ['name'],
            },
        ),
    ]
