# Generated by Django 5.0.14 on 2026-08-15 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('last_watched_second', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('ended', 'Ended')], default='active', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_sessions', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_sessions', to='movies.movie')),
            ],
            options={
                'db_table': 'stream_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'video'], name='stream_sess_user_id_631ca0_idx'), models.Index(fields=['expires_at'], name='stream_sess_expires_3ebcba_idx'), models.Index(fields=['status'], name='stream_sess_status_a9f2e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_watched_second', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to='movies.movie')),
            ],
            options={
                'db_table': 'watch_progress',
                'ordering': ['-last_watched_at'],
                'indexes': [models.Index(fields=['user', 'video'], name='watch_progr_user_id_5e02c1_idx'), models.Index(fields=['user', '-last_watched_at'], name='watch_progr_user_id_2ed812_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='watchprogress',
            constraint=models.UniqueConstraint(fields=('user', 'video'), name='unique_user_video_progress'),
        ),
    ]
