# Generated by Django 5.2.7 on 2026-08-08 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Price paid', max_digits=6)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('transaction_id', models.CharField(blank=True, help_text='Wallet transaction reference', max_length=100, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movie Purchase',
                'verbose_name_plural': 'Movie Purchases',
                'ordering': ['-purchase_date'],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
