# Generated by Django 5.0.14 on 2026-08-19 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='accounts_us_email_f69303_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone', 'is_phone_verified'], name='accounts_us_phone_89c812_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'is_active', 'expires_at'], name='accounts_su_user_id_9e6548_idx'),
        ),
    ]
