# Generated by Django 5.2.7 on 2026-08-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'ordering': ['sort_order', 'price']},
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='is_highlighted',
            field=models.BooleanField(default=False, help_text="Show as 'Most popular'"),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days the membership is valid. Leave blank for the Free tier (no expiry).', null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
