# Generated by Django 5.0.14 on 2026-08-15 05:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('release_date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('video_upload', models.FileField(blank=True, help_text='Upload video file directly (MP4, MOV, MKV, WebM)', max_length=255, null=True, upload_to='movies/videos/')),
                ('video_file', models.URLField(blank=True, help_text='Bunny.net video URL', null=True)),
                ('bunny_video_id', models.CharField(blank=True, help_text='Bunny Stream Video ID', max_length=255, null=True)),
                ('poster', models.ImageField(upload_to='movies/posters/')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='movies/backdrops/')),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('access_type', models.CharField(choices=[('free', 'Free'), ('member', 'Membership Required'), ('purchase', 'Pay Per View')], default='free', max_length=10)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text="Required if access_type is 'purchase'", max_digits=6, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Average rating (0-10)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in hero banner / featured sections')),
                ('is_new_release', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cast', models.ManyToManyField(blank=True, related_name='movies', to='taxonomy.cast')),
                ('categories', models.ManyToManyField(related_name='movies', to='taxonomy.category')),
                ('crew', models.ManyToManyField(blank=True, related_name='movies', to='taxonomy.crew')),
                ('genres', models.ManyToManyField(related_name='movies', to='taxonomy.genre')),
            ],
            options={
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner headline text', max_length=255)),
                ('subtitle', models.TextField(blank=True, help_text='Optional subtitle')),
                ('image', models.ImageField(help_text='Recommended: 1600×900', upload_to='content/banners/')),
                ('link_type', models.CharField(choices=[('movie', 'Movie (Internal)'), ('external', 'External URL'), ('none', 'No Link')], default='movie', max_length=10)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, help_text='Auto-generated from movie or external_url')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_banners', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('video_file_id', models.CharField(help_text='Bunny.net video ID or GUID', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='episodes/thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.movie')),
            ],
            options={
                'ordering': ['movie', 'episode_number'],
                'unique_together': {('movie', 'episode_number')},
            },
        ),
    ]
