# Generated by Django 5.0.14 on 2026-08-19 09:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True, max_length=500)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/posters/')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='movies/backdrops/')),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('video_file', models.URLField(blank=True, help_text='Bunny.net embed URL', null=True)),
                ('bunny_video_id', models.CharField(blank=True, max_length=255, null=True)),
                ('video_upload', models.FileField(blank=True, null=True, upload_to='movies/videos/')),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('documentary', 'Documentary'), ('anime', 'Anime')], db_index=True, default='movie', max_length=20)),
                ('access_type', models.CharField(choices=[('free', 'Free'), ('member', 'Member Only'), ('purchase', 'Pay Per View')], db_index=True, default='free', max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('country', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('view_count', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_episodes', models.IntegerField(blank=True, null=True)),
                ('has_khmer_dub', models.BooleanField(default=False)),
                ('has_khmer_sub', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_new_release', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='movies', to='taxonomy.category')),
                ('countries', models.ManyToManyField(blank=True, related_name='movies', to='taxonomy.country')),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='taxonomy.genre')),
                ('series_types', models.ManyToManyField(blank=True, related_name='movies', to='taxonomy.seriestype')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('link_type', models.CharField(choices=[('movie', 'Movie'), ('external', 'External URL')], default='movie', max_length=20)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('episode_number', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('video_file', models.URLField(blank=True, null=True)),
                ('bunny_video_id', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='movies/episodes/')),
                ('view_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['episode_number'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'is_active'], name='movies_movi_title_47a5a4_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['access_type', 'is_active'], name='movies_movi_access__fd7475_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['content_type', 'is_active'], name='movies_movi_content_2693da_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-created_at', 'is_active'], name='movies_movi_created_a174ca_idx'),
        ),
        migrations.AddIndex(
            model_name='herobanner',
            index=models.Index(fields=['is_active', 'order'], name='movies_hero_is_acti_5c7f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['movie', 'episode_number'], name='movies_epis_movie_i_1e7ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['movie', 'is_active'], name='movies_epis_movie_i_1a650b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('movie', 'episode_number')},
        ),
    ]
