# Generated by Django 5.2.7 on 2026-08-08 11:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cast/')),
                ('character_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Cast',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('director', 'Director'), ('producer', 'Producer'), ('writer', 'Writer'), ('cinematographer', 'Cinematographer'), ('composer', 'Composer'), ('other', 'Other')], default='other', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crew/')),
            ],
            options={
                'verbose_name_plural': 'Crew',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('release_date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('poster', models.ImageField(upload_to='movies/posters/')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='movies/backdrops/')),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('access_type', models.CharField(choices=[('free', 'Free'), ('member', 'Membership Required'), ('purchase', 'Pay Per View')], default='free', max_length=10)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text="Required if access_type is 'purchase'", max_digits=6, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Average rating (0-10)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in hero banner / featured sections')),
                ('is_new_release', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cast', models.ManyToManyField(blank=True, related_name='movies', to='movies.cast')),
                ('categories', models.ManyToManyField(related_name='movies', to='movies.category')),
                ('crew', models.ManyToManyField(blank=True, related_name='movies', to='movies.crew')),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
            ],
            options={
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('video_file_id', models.CharField(help_text='Bunny.net video ID or GUID', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='episodes/thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.movie')),
            ],
            options={
                'ordering': ['movie', 'episode_number'],
                'unique_together': {('movie', 'episode_number')},
            },
        ),
    ]
