# Generated by Django 5.2.7 on 2026-08-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, help_text='Bunny.net video file', null=True, upload_to='movies/videos/'),
        ),
    ]
