# Generated by Django 5.0.14 on 2026-08-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=300, unique=True),
        ),
    ]
