# Generated by Django 5.0.14 on 2026-08-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='bunny_video_id',
            field=models.CharField(blank=True, help_text='Bunny Stream Video ID', max_length=255, null=True),
        ),
    ]
