# Generated by Django 5.0.14 on 2026-08-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_slug'),
        ('taxonomy', '0005_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='content_type',
            field=models.CharField(choices=[('movie', 'រឿងដុំ'), ('tv_show', 'រឿងភាគ')], default='movie', help_text='ជ្រើសរើសថាជារឿងដុំ ឬរឿងភាគ', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='ប្រទេសដូចជា ខ្មែរ ចិន កូរេ ជាដើម', related_name='movies', to='taxonomy.country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='has_khmer_dub',
            field=models.BooleanField(default=False, help_text='ធីកបើមានសំឡេងនិយាយខ្មែរ'),
        ),
        migrations.AddField(
            model_name='movie',
            name='has_khmer_sub',
            field=models.BooleanField(default=False, help_text='ធីកបើមានអក្សររត់ពីក្រោមខ្មែរ'),
        ),
    ]
