# Generated by Django 5.0.14 on 2026-08-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_bunny_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.URLField(blank=True, help_text='Bunny.net video URL', null=True),
        ),
    ]
