# Generated by Django 5.0.14 on 2026-08-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_content_type_movie_countries_and_more'),
        ('taxonomy', '0006_seriestype'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='series_types',
            field=models.ManyToManyField(blank=True, help_text='ប្រភេទរឿងភាគដូចជា រឿងភាគចិន ហូលីវូត ជាដើម (សម្រាប់ TV Shows)', related_name='movies', to='taxonomy.seriestype'),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_episodes',
            field=models.PositiveIntegerField(blank=True, help_text='ចំនួនភាគសរុប (សម្រាប់ TV Shows)', null=True),
        ),
    ]
