# Generated by Django 5.0.14 on 2026-08-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_series_types_movie_total_episodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag', models.CharField(blank=True, max_length=10)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
