# Generated by Django 5.0.14 on 2026-08-12 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner headline text', max_length=255)),
                ('subtitle', models.TextField(blank=True, help_text='Optional subtitle')),
                ('image', models.ImageField(help_text='Recommended: 1600×900', upload_to='content/banners/')),
                ('link_type', models.CharField(choices=[('movie', 'Movie (Internal)'), ('external', 'External URL'), ('none', 'No Link')], default='movie', max_length=10)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, help_text='Auto-generated from movie or external_url')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_banners', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
