# Generated by Django 5.0.14 on 2026-08-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_herobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_upload',
            field=models.FileField(blank=True, help_text='Upload video file directly (MP4, MOV, MKV, WebM)', null=True, upload_to='movies/videos/'),
        ),
    ]
