# Generated by Django 5.0.14 on 2026-08-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_video_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_upload',
            field=models.FileField(blank=True, help_text='Upload video file directly (MP4, MOV, MKV, WebM)', max_length=255, null=True, upload_to='movies/videos/'),
        ),
    ]
